apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-app
spec:
  project: default

  source:
    repoURL: https://github.com/magicskunk/service-cicd-k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: magicskunk-cicd-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
